// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";
import NavigationItem from './NavigationItem';

export const components = {
  //navigation_item: dynamic(() => import("./NavigationItem")),
  navigation_item: NavigationItem,
};
